### ISSUE TITLE
Locale Autoswitch Class

### ISSUE THREAD

**Issue by naftalimurgor** [cocoytech/CI3-ultimate#8]
A Locale/language class(Library) that:-
1. Autoswitches to browser default language
2. Or defaults to English

**Comment by CurlyBytes** [comment]
Will work this one after task of #5, #6 and #7

**Comment by naftalimurgor** [comment]
Alright.

**Comment by CurlyBytes** [comment]
Check PR #21 and check out the master, added the multilanguage on controller layer by overriding the core controller, as of now it has default language English and Tagalog for example, hope this resolves the concern ^^

**Comment by CurlyBytes** [comment]
@slax425  Will always to improve time to time, feel free to submit PRs too! and highly appreciated
